name: "âœ¨ Prep release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The new version"
        type: "string"
        required: true

jobs:
  prep-release:
    name: "Prep release v${{ inputs.version }}"

    permissions:
      contents: "write"
      pull-requests: "write"

    strategy:
      matrix:
        include:
          - tox-label-create-changes: "prep-release"
            branch-name: "release/$VERSION"
            commit-title: "Update project metadata"
            pr-base: "releases"
            pr-title: "Release v$VERSION"

    uses: "kurtmckee/github-workflows/.github/workflows/create-pr.yaml@a8716fc28daeb38133a50ef8dce70df9c65988ad" # v1.5
    with:
      config: "${{ toJSON(matrix) }}"
      version: "${{ inputs.version }}"
